add pod annotations to promex
spacelift-io/spacelift-helm-charts pull request #75
Opened 2024-08-28 21:56 UTC by akmal-spacelift

- [ ] A chart version is updated
  - [ ] No changes on CRDs
  - [ ] CRDs are updated

2024-08-28 22:05 UTC, akmal-spacelift commented
internal ref: https://spacelift-io.slack.com/archives/C0552G4THAM/p1724879665267479

2024-08-29 08:22 UTC, eliecharra requested changes

2024-08-29 08:22 UTC, eliecharra commented on spacelift-promex/templates/deployment.yaml
> +      {{- end }}
```suggestion
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

I think the indentation is incorrect here. You can see the result if you run `helm template .` from this folder locally.

![image](https://github.com/user-attachments/assets/6bce22f7-9b7b-49b3-9cb6-53a68daca5f3)

2024-08-30 07:49 UTC, eliecharra approved these changes

2024-08-30 18:03 UTC, merged